/**
 * GENERATED by scripts/generate-native-trust.mjs — do not edit.
 * Embedded trust anchor for package-relative ProcessHost helper.
 * Contains only deterministic hash/length/machine (no absolute paths).
 */
export const EMBEDDED_NATIVE_HELPER_SHA256 =
  "f821cdf1659f4d55d6072b3838444957d175bbc1b9c2b9385493d16b0882f8f1" as const;
export const EMBEDDED_NATIVE_HELPER_BYTE_LENGTH = 73525322 as const;
export const EMBEDDED_NATIVE_HELPER_PE_MACHINE = 0x8664 as const;
export const EMBEDDED_NATIVE_HELPER_PLATFORM = 'win-x64' as const;
export const EMBEDDED_NATIVE_HELPER_FILE_NAME =
  'triagent-process-host.exe' as const;
export const EMBEDDED_NATIVE_HELPER_RELATIVE_PATH =
  'dist/native/win-x64/triagent-process-host.exe' as const;
